/**
 * Gemini `responseSchema` for structured music generation.
 * Keep in sync with {@link validateMusicParams} / {@link parseMoodSignalIntent} via contract tests.
 */
export const GEMINI_MUSIC_RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    baseFrequency: { type: "NUMBER", description: "Frequency in Hz (e.g. 50 to 300)" },
    chordIntervals: {
      type: "ARRAY",
      items: { type: "NUMBER" },
      description: "Array of semitone intervals, e.g. [0, 7, 12, 16]",
    },
    filterCutoffMax: { type: "NUMBER", description: "Max filter frequency in Hz (e.g. 400 to 3000)" },
    lfoSpeed: { type: "NUMBER", description: "LFO speed in Hz (e.g. 0.01 to 0.5)" },
    reverbWet: { type: "NUMBER", description: "Reverb wet level from 0 to 1" },
    volume: { type: "NUMBER", description: "Volume in decibels (e.g. -20 to -5)" },
    droneVolume: { type: "NUMBER", description: "Drone volume in decibels (-60 to 0)" },
    padVolume: { type: "NUMBER", description: "Pad volume in decibels (-60 to 0)" },
    arpVolume: { type: "NUMBER", description: "Arp volume in decibels (-60 to 0)" },
    bellVolume: { type: "NUMBER", description: "Bell volume in decibels (-60 to 0)" },
    subVolume: { type: "NUMBER", description: "Sub bass volume in decibels (-60 to 0)" },
    colorPalette: {
      type: "ARRAY",
      items: { type: "STRING" },
      description: "Array of 3 hex color strings",
    },
    oscillatorType: { type: "STRING", description: "sine, triangle, square, or sawtooth" },
    harmonicity: { type: "NUMBER", description: "0.1 to 5.0" },
    modulationIndex: { type: "NUMBER", description: "0 to 10" },
    noiseAmount: { type: "NUMBER", description: "0.0 to 1.0" },
    noiseType: { type: "STRING", description: "white, pink, or brown" },
    delayTime: { type: "STRING", description: "8n, 4n, or 2n" },
    delayFeedback: { type: "NUMBER", description: "0.0 to 0.9" },
    complexity: { type: "NUMBER", description: "density of generative notes from 0.0 to 1.0" },
    attackTime: { type: "NUMBER", description: "0.1 to 10.0" },
    releaseTime: { type: "NUMBER", description: "0.1 to 20.0" },
    reverbDecay: { type: "NUMBER", description: "1.0 to 20.0" },
    chorusDepth: { type: "NUMBER", description: "0.0 to 1.0" },
    phaserFrequency: { type: "NUMBER", description: "0.1 to 10.0" },
    moodSignalIntent: {
      type: "OBJECT",
      description: "Normalized affect dimensions from 0 to 1",
      properties: {
        arousal: { type: "NUMBER" },
        valence: { type: "NUMBER" },
        tension: { type: "NUMBER" },
        cognitiveLoad: { type: "NUMBER" },
        grounding: { type: "NUMBER" },
      },
      required: ["arousal", "valence", "tension", "cognitiveLoad", "grounding"],
    },
    feedbackPrompt: {
      type: "OBJECT",
      properties: {
        question: { type: "STRING", description: "A subtle, thoughtful check-in question." },
        options: {
          type: "ARRAY",
          items: { type: "STRING" },
          description: "Exactly 3 distinct answer options.",
        },
      },
      required: ["question", "options"],
    },
  },
  required: [
    "baseFrequency",
    "chordIntervals",
    "filterCutoffMax",
    "lfoSpeed",
    "reverbWet",
    "volume",
    "droneVolume",
    "padVolume",
    "arpVolume",
    "bellVolume",
    "subVolume",
    "colorPalette",
    "oscillatorType",
    "harmonicity",
    "modulationIndex",
    "noiseAmount",
    "noiseType",
    "delayTime",
    "delayFeedback",
    "complexity",
    "attackTime",
    "releaseTime",
    "reverbDecay",
    "chorusDepth",
    "phaserFrequency",
    "moodSignalIntent",
    "feedbackPrompt",
  ],
} as const;
